### ISSUE TITLE
feature: transform priorities

### ISSUE THREAD

**Issue by broccolai** [Incendo/interfaces#15]
allow transformations to set their order (akin to z-index in css)

**Comment by Citymonstret** [comment]
this should be done so that the transformations are "merged" in memory before applied to the interface, so that we don't need to set items multiple times in the interface

**Comment by kadenscott** [comment]
> this should be done so that the transformations are "merged" in memory before applied to the interface, so that we don't need to set items multiple times in the interface

can't wait for the interfaces vdom
