### ISSUE TITLE
Snapshot repo is not working

### ISSUE THREAD

**Issue by SentixDev** [Incendo/interfaces#72]
The specified snapshot repository seems to be no longer accessible. Could you guys & gals move it to sonatype aswell please?

**Comment by DaRacci** [comment]
I've uploaded the latest artifact to my repo at https://repo.racci.dev/snapshots if you need it in the meantime

**Comment by jpenilla** [comment]
Snapshots have been moved to sonatype, `https://oss.sonatype.org/content/repositories/snapshots/`
